import { createGameFromMoves } from '../createGameFromMoves';

test('Test that game is correctly initialized', () => {
  expect(createGameFromMoves([])).toStrictEqual({
    board: {
      a1: null,
      a2: null,
      a3: null,
      a4: null,
      a5: null,
      a6: null,
      a7: null,
      a8: null,
      a9: null,
      b1: null,
      b2: null,
      b3: null,
      b4: null,
      b5: null,
      b6: null,
      b7: null,
      b8: null,
      b9: null,
      c1: null,
      c2: null,
      c3: null,
      c4: null,
      c5: null,
      c6: null,
      c7: null,
      c8: null,
      c9: null,
      d1: null,
      d2: null,
      d3: null,
      d4: null,
      d5: null,
      d6: null,
      d7: null,
      d8: null,
      d9: null,
      e1: 1,
      e2: null,
      e3: null,
      e4: null,
      e5: null,
      e6: null,
      e7: null,
      e8: null,
      e9: 2,
      f1: null,
      f2: null,
      f3: null,
      f4: null,
      f5: null,
      f6: null,
      f7: null,
      f8: null,
      f9: null,
      g1: null,
      g2: null,
      g3: null,
      g4: null,
      g5: null,
      g6: null,
      g7: null,
      g8: null,
      g9: null,
      h1: null,
      h2: null,
      h3: null,
      h4: null,
      h5: null,
      h6: null,
      h7: null,
      h8: null,
      h9: null,
      i1: null,
      i2: null,
      i3: null,
      i4: null,
      i5: null,
      i6: null,
      i7: null,
      i8: null,
      i9: null,
      a1h: false,
      a1v: false,
      a2h: false,
      a2v: false,
      a3h: false,
      a3v: false,
      a4h: false,
      a4v: false,
      a5h: false,
      a5v: false,
      a6h: false,
      a6v: false,
      a7h: false,
      a7v: false,
      a8h: false,
      a8v: false,
      b1h: false,
      b1v: false,
      b2h: false,
      b2v: false,
      b3h: false,
      b3v: false,
      b4h: false,
      b4v: false,
      b5h: false,
      b5v: false,
      b6h: false,
      b6v: false,
      b7h: false,
      b7v: false,
      b8h: false,
      b8v: false,
      c1h: false,
      c1v: false,
      c2h: false,
      c2v: false,
      c3h: false,
      c3v: false,
      c4h: false,
      c4v: false,
      c5h: false,
      c5v: false,
      c6h: false,
      c6v: false,
      c7h: false,
      c7v: false,
      c8h: false,
      c8v: false,
      d1h: false,
      d1v: false,
      d2h: false,
      d2v: false,
      d3h: false,
      d3v: false,
      d4h: false,
      d4v: false,
      d5h: false,
      d5v: false,
      d6h: false,
      d6v: false,
      d7h: false,
      d7v: false,
      d8h: false,
      d8v: false,
      e1h: false,
      e1v: false,
      e2h: false,
      e2v: false,
      e3h: false,
      e3v: false,
      e4h: false,
      e4v: false,
      e5h: false,
      e5v: false,
      e6h: false,
      e6v: false,
      e7h: false,
      e7v: false,
      e8h: false,
      e8v: false,
      f1h: false,
      f1v: false,
      f2h: false,
      f2v: false,
      f3h: false,
      f3v: false,
      f4h: false,
      f4v: false,
      f5h: false,
      f5v: false,
      f6h: false,
      f6v: false,
      f7h: false,
      f7v: false,
      f8h: false,
      f8v: false,
      g1h: false,
      g1v: false,
      g2h: false,
      g2v: false,
      g3h: false,
      g3v: false,
      g4h: false,
      g4v: false,
      g5h: false,
      g5v: false,
      g6h: false,
      g6v: false,
      g7h: false,
      g7v: false,
      g8h: false,
      g8v: false,
      h1h: false,
      h1v: false,
      h2h: false,
      h2v: false,
      h3h: false,
      h3v: false,
      h4h: false,
      h4v: false,
      h5h: false,
      h5v: false,
      h6h: false,
      h6v: false,
      h7h: false,
      h7v: false,
      h8h: false,
      h8v: false,
    },
    pieceMatrix: {
      a: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      b: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      c: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      d: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      e: { 1: 1, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 2 },
      f: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      g: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      h: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      i: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
    },
    wallMatrix: {
      a: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      b: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      c: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      d: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      e: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      f: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      g: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      h: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
    },
    history: [],
    turn: 1,
    playerPositions: { 1: { x: 'e', y: 1 }, 2: { x: 'e', y: 9 } },
    playerWallCounts: { 1: 10, 2: 10 },
  });
});

test('Test that game is correctly initialized from array of forward moves', () => {
  expect(createGameFromMoves(['e2', 'e8', 'e3', 'e7'])).toStrictEqual({
    board: {
      a1: null,
      a2: null,
      a3: null,
      a4: null,
      a5: null,
      a6: null,
      a7: null,
      a8: null,
      a9: null,
      b1: null,
      b2: null,
      b3: null,
      b4: null,
      b5: null,
      b6: null,
      b7: null,
      b8: null,
      b9: null,
      c1: null,
      c2: null,
      c3: null,
      c4: null,
      c5: null,
      c6: null,
      c7: null,
      c8: null,
      c9: null,
      d1: null,
      d2: null,
      d3: null,
      d4: null,
      d5: null,
      d6: null,
      d7: null,
      d8: null,
      d9: null,
      e1: null,
      e2: null,
      e3: 1,
      e4: null,
      e5: null,
      e6: null,
      e7: 2,
      e8: null,
      e9: null,
      f1: null,
      f2: null,
      f3: null,
      f4: null,
      f5: null,
      f6: null,
      f7: null,
      f8: null,
      f9: null,
      g1: null,
      g2: null,
      g3: null,
      g4: null,
      g5: null,
      g6: null,
      g7: null,
      g8: null,
      g9: null,
      h1: null,
      h2: null,
      h3: null,
      h4: null,
      h5: null,
      h6: null,
      h7: null,
      h8: null,
      h9: null,
      i1: null,
      i2: null,
      i3: null,
      i4: null,
      i5: null,
      i6: null,
      i7: null,
      i8: null,
      i9: null,
      a1h: false,
      a1v: false,
      a2h: false,
      a2v: false,
      a3h: false,
      a3v: false,
      a4h: false,
      a4v: false,
      a5h: false,
      a5v: false,
      a6h: false,
      a6v: false,
      a7h: false,
      a7v: false,
      a8h: false,
      a8v: false,
      b1h: false,
      b1v: false,
      b2h: false,
      b2v: false,
      b3h: false,
      b3v: false,
      b4h: false,
      b4v: false,
      b5h: false,
      b5v: false,
      b6h: false,
      b6v: false,
      b7h: false,
      b7v: false,
      b8h: false,
      b8v: false,
      c1h: false,
      c1v: false,
      c2h: false,
      c2v: false,
      c3h: false,
      c3v: false,
      c4h: false,
      c4v: false,
      c5h: false,
      c5v: false,
      c6h: false,
      c6v: false,
      c7h: false,
      c7v: false,
      c8h: false,
      c8v: false,
      d1h: false,
      d1v: false,
      d2h: false,
      d2v: false,
      d3h: false,
      d3v: false,
      d4h: false,
      d4v: false,
      d5h: false,
      d5v: false,
      d6h: false,
      d6v: false,
      d7h: false,
      d7v: false,
      d8h: false,
      d8v: false,
      e1h: false,
      e1v: false,
      e2h: false,
      e2v: false,
      e3h: false,
      e3v: false,
      e4h: false,
      e4v: false,
      e5h: false,
      e5v: false,
      e6h: false,
      e6v: false,
      e7h: false,
      e7v: false,
      e8h: false,
      e8v: false,
      f1h: false,
      f1v: false,
      f2h: false,
      f2v: false,
      f3h: false,
      f3v: false,
      f4h: false,
      f4v: false,
      f5h: false,
      f5v: false,
      f6h: false,
      f6v: false,
      f7h: false,
      f7v: false,
      f8h: false,
      f8v: false,
      g1h: false,
      g1v: false,
      g2h: false,
      g2v: false,
      g3h: false,
      g3v: false,
      g4h: false,
      g4v: false,
      g5h: false,
      g5v: false,
      g6h: false,
      g6v: false,
      g7h: false,
      g7v: false,
      g8h: false,
      g8v: false,
      h1h: false,
      h1v: false,
      h2h: false,
      h2v: false,
      h3h: false,
      h3v: false,
      h4h: false,
      h4v: false,
      h5h: false,
      h5v: false,
      h6h: false,
      h6v: false,
      h7h: false,
      h7v: false,
      h8h: false,
      h8v: false,
    },
    pieceMatrix: {
      a: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      b: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      c: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      d: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      e: { 1: 0, 2: 0, 3: 1, 4: 0, 5: 0, 6: 0, 7: 2, 8: 0, 9: 0 },
      f: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      g: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      h: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
      i: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 },
    },
    wallMatrix: {
      a: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      b: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      c: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      d: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      e: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      f: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      g: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
      h: {
        1: { h: false, v: false },
        2: { h: false, v: false },
        3: { h: false, v: false },
        4: { h: false, v: false },
        5: { h: false, v: false },
        6: { h: false, v: false },
        7: { h: false, v: false },
        8: { h: false, v: false },
      },
    },
    history: ['e2', 'e8', 'e3', 'e7'],
    turn: 1,
    playerPositions: {
      1: {
        x: 'e',
        y: 3,
        previousPosition: { x: 'e', y: 2, previousPosition: { x: 'e', y: 1 } },
      },
      2: {
        x: 'e',
        y: 7,
        previousPosition: { x: 'e', y: 8, previousPosition: { x: 'e', y: 9 } },
      },
    },
    playerWallCounts: { 1: 10, 2: 10 },
  });
});
