import { createGameFromMoves } from '../createGameFromMoves';
import { createNewGame } from '../createNewGame';
import { getValidMoveArray } from '../getValidMoveArray';
import { isMoveInteresting } from '../isMoveInteresting';

test('Test interesting moves are correctly identified at the beginning of the game', () => {
  const game = createNewGame();
  expect(
    new Set(
      getValidMoveArray(game).filter((move) => isMoveInteresting(game, move)),
    ),
  ).toEqual(
    new Set([
      'e2',
      'f1',
      'd1',
      'a1h',
      'a1v',
      'a2h',
      'a3h',
      'a4h',
      'a5h',
      'a6h',
      'a7h',
      'a8h',
      'a8v',
      'b1v',
      'b8v',
      'c1h',
      'c1v',
      'c8v',
      'd1h',
      'd1v',
      'd2h',
      'd2v',
      'd3h',
      'd3v',
      'd4h',
      'd4v',
      'd5h',
      'd5v',
      'd6h',
      'd6v',
      'd7h',
      'd7v',
      'd8h',
      'd8v',
      'e1h',
      'e1v',
      'e2h',
      'e2v',
      'e3h',
      'e3v',
      'e4h',
      'e4v',
      'e5h',
      'e5v',
      'e6h',
      'e6v',
      'e7h',
      'e7v',
      'e8h',
      'e8v',
      'f1v',
      'f8v',
      'g1v',
      'g8v',
      'h1h',
      'h1v',
      'h2h',
      'h3h',
      'h4h',
      'h5h',
      'h6h',
      'h7h',
      'h8h',
      'h8v',
    ]),
  );
});
